# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
fos_ck_editor:
    configs:
        default_config:
            toolbar:
                - { name: 'clipboard', items: ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo']}
                - { name: 'editing', items: ['Find', 'Replace', '-', 'SelectAll']}
                - { name: 'basicstyles', items: ['Bold', 'Italic', 'Underline', 'Strike', '-', 'RemoveFormat']}
                - { name: 'paragraph', items: ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', 
                '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock']}
                - { name: 'links', items: ['Link', 'Unlink', 'Anchor']}
                - { name: 'insert', items: ['Image', 'Table', 'HorizontalRule', 'SpecialChar']}
                - '/'
                - { name: 'styles', items: ['Styles', 'Format', 'Font', 'FontSize']}
                - { name: 'colors', items: ['TextColor', 'BGColor']}
                - { name: 'tools', items: ['Maximize']}