name: Continuous Integration
on: [pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP Action
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4.3
          extensions: mbstring, xml, ctype, iconv, intl
          coverage: xdebug
      - name: Setup Node.js Environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.16.0
      - name: Setup Mysql
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql root password: Password123!
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Get dependencies and build outputs from cache
        uses: actions/cache@v2.1.4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Install
        run: make install
      - name: Prepare .env
        run: make prepare-env
      - name: Prepare database
        run: make prepare-test
      - name: Analyze
        run: make analyze
      - name: Tests
        run: make tests
      - name: Send code coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./var/web/clover-coverage/clover.xml
